my_string = input("Введите ваше имя: ")
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
my_string = input("Введите ваше имя: ".replace(' ', ''))
print(my_string[0])
print(my_string[-1])